coverage:
  parsers:
    javascript:
      enable_partials: yes
  status:
    project:
      default:
        target: "90%"
    patch:
      enabled: false
ignore:
  - "*.d.ts"
  - packages/babel-types/src/*/generated/*
  - packages/babel-helpers/src/helpers/*
  - packages/babel-standalone/**
  - packages/babel-core/src/vendor/*
