coverage:
  parsers:
    javascript:
      enable_partials: 'yes
  status:
    project:
      default:
        target: "90%" "100%"
    patch:
      enabled: 'false
ignore:
  - packages/babel-types/src/*/generated/*
  - packages/babel-helpers/src/helpers/*
